/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getSnapshot(): SpectrumFrame | null

export declare function getStatus(): SpectrumStatus

export interface SpectrumFrame {
  source: string
  state: string
  timestamp: number
  timePos?: number
  sampleRate: number
  fftSize: number
  minFrequency: number
  maxFrequency: number
  bins: Array<number>
  waveform?: Array<number>
  rms: number
  peak: number
}

export interface SpectrumOptions {
  fps?: number
  binCount?: number
  fftSize?: number
  smoothing?: number
  minFrequency?: number
  maxFrequency?: number
  scale?: string
  includeWaveform?: boolean
}

export interface SpectrumStatus {
  available: boolean
  running: boolean
  provider: string
  reason?: string
  subscriberCount?: number
}

export declare function start(options?: SpectrumOptions | undefined | null): SpectrumStatus

export declare function stop(): SpectrumStatus
