/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function close(): void

export declare function historyClear(): NativeResult<string>

export declare function historyGetEntries(payloadJson?: string | undefined | null): NativeResult<string>

export declare function historyRecordPlay(payloadJson: string): NativeResult<string>

export declare function historyRemoveEntries(payloadJson: string): NativeResult<string>

export declare function initialize(databasePath: string): NativeResult<undefined>

export declare function kvDelete(key: string): NativeResult<undefined>

export declare function kvGet(key: string): NativeResult<string | undefined | null>

export declare function kvSet(key: string, valueJson: string): NativeResult<undefined>

export declare function playbackAppendQueueItems(payloadJson: string): NativeResult<string>

export declare function playbackClearQueue(payloadJson: string): NativeResult<string>

export declare function playbackGetQueue(payloadJson: string): NativeResult<string | undefined | null>

export declare function playbackGetSnapshot(hydrateAllSongs?: boolean | undefined | null): NativeResult<string>

export declare function playbackRemoveQueue(payloadJson: string): NativeResult<string>

export declare function playbackRemoveQueueItem(payloadJson: string): NativeResult<string>

export declare function playbackReorderQueueItems(payloadJson: string): NativeResult<string>

export declare function playbackReplaceQueue(payloadJson: string): NativeResult<string>

export declare function playbackSetActiveQueue(queueId: string): NativeResult<string>

export declare function playbackSetQueueCurrentTrack(payloadJson: string): NativeResult<string>

export declare function playbackUpdateQueueMeta(payloadJson: string): NativeResult<string>

export declare function pluginSqliteAll(databaseId: string, sql: string, paramsJson?: string | undefined | null, limit?: number | undefined | null): NativeResult<string>

export declare function pluginSqliteClose(databaseId: string): NativeResult<string>

export declare function pluginSqliteCloseByPrefix(prefix: string): NativeResult<string>

export declare function pluginSqliteExec(databaseId: string, sql: string): NativeResult<string>

export declare function pluginSqliteOpen(databaseId: string, databasePath: string, optionsJson?: string | undefined | null): NativeResult<string>

export declare function pluginSqliteRun(databaseId: string, sql: string, paramsJson?: string | undefined | null): NativeResult<string>

export declare function pluginSqliteTransaction(databaseId: string, statementsJson: string): NativeResult<string>

export declare function resetAll(): NativeResult<undefined>
