/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function close(): void

export declare function initialize(databasePath: string): NativeResult<undefined>

export declare function kvDelete(key: string): NativeResult<undefined>

export declare function kvGet(key: string): NativeResult<string | undefined | null>

export declare function kvSet(key: string, valueJson: string): NativeResult<undefined>

export declare function playbackAppendQueueItems(payloadJson: string): NativeResult<string>

export declare function playbackClearQueue(payloadJson: string): NativeResult<string>

export declare function playbackGetQueue(payloadJson: string): NativeResult<string | undefined | null>

export declare function playbackGetSnapshot(hydrateAllSongs?: boolean | undefined | null): NativeResult<string>

export declare function playbackRemoveQueue(payloadJson: string): NativeResult<string>

export declare function playbackRemoveQueueItem(payloadJson: string): NativeResult<string>

export declare function playbackReorderQueueItems(payloadJson: string): NativeResult<string>

export declare function playbackReplaceQueue(payloadJson: string): NativeResult<string>

export declare function playbackSetActiveQueue(queueId: string): NativeResult<string>

export declare function playbackSetQueueCurrentTrack(payloadJson: string): NativeResult<string>

export declare function playbackUpdateQueueMeta(payloadJson: string): NativeResult<string>

export declare function resetAll(): NativeResult<undefined>
