/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function afCommand(label: string, cmd: string, arg: string, target: string): void

export interface AudioDevice {
  name: string
  description: string
}

export declare function cancelFade(): void

export declare function destroy(): void

export declare function fade(from: number, to: number, durationMs: number): void

export declare function getAudioDevices(): Array<AudioDevice>

export declare function getProperty(name: string): string

export declare function getSpectrumSnapshot(): SpectrumFrame | null

export declare function getSpectrumStatus(): SpectrumStatus

export declare function getState(): PlayerState

export declare function getTrackList(): Array<TrackInfo>

export declare function initialize(runtimePath: string): void

export declare function isFading(): boolean

export declare function loadFile(url: string): void

export declare function loadMkvTrack(url: string, trackId: number): void

export declare function pause(): void

export declare function pauseWithFade(savedVolume: number, durationMs: number): void

export declare function play(): void

export interface PlayerEvent {
  type: string
  value?: number
  flag?: boolean
  message?: string
  devices?: Array<AudioDevice>
  prefix?: string
  level?: string
}

export interface PlayerState {
  playing: boolean
  paused: boolean
  duration: number
  timePos: number
  volume: number
  speed: number
  idle: boolean
  path: string
  audioDevice: string
  audioTrackId: number
}

export declare function playWithFade(targetVolume: number, durationMs: number): void

export declare function registerEventHandler(callback: ((err: Error | null, arg: PlayerEvent) => any)): void

export declare function seek(time: number): void

export declare function setAudioDevice(deviceName: string): void

export declare function setAudioFilter(filter: string): void

export declare function setAudioTrack(trackId: number): void

export declare function setEq(gains: Array<number>): void

export declare function setExclusive(exclusive: boolean): void

export declare function setLoopFile(value: string): void

export declare function setMediaTitle(title: string): void

export declare function setNormalizationGain(gainDb: number): void

export declare function setSpeed(speed: number): void

export declare function setVolume(volume: number): void

export interface SpectrumFrame {
  source: string
  state: string
  timestamp: number
  timePos?: number
  sampleRate: number
  fftSize: number
  minFrequency: number
  maxFrequency: number
  bins: Array<number>
  waveform?: Array<number>
  rms: number
  peak: number
}

export interface SpectrumOptions {
  fps?: number
  binCount?: number
  fftSize?: number
  smoothing?: number
  minFrequency?: number
  maxFrequency?: number
  scale?: string
  includeWaveform?: boolean
}

export interface SpectrumStatus {
  available: boolean
  running: boolean
  provider: string
  reason?: string
  subscriberCount?: number
}

export declare function startSpectrum(options?: SpectrumOptions | undefined | null): SpectrumStatus

export declare function stop(): void

export declare function stopSpectrum(): SpectrumStatus

export interface TrackInfo {
  id: number
  type: string
  codec: string
  title?: string
  lang?: string
}
