/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AudioDevice {
  name: string
  description: string
}

export declare function cancelFade(): void

export declare function clearPreparedNextSource(): void

export declare function configureSpectrum(options?: SpectrumOptions | undefined | null): SpectrumStatus

export declare function destroy(): void

export declare function fade(from: number, to: number, durationMs: number): Promise<unknown>

export declare function getAudioDevices(): Promise<unknown>

export declare function getAudioFilter(): string

export declare function getSpectrumSnapshot(): Promise<unknown>

export declare function getSpectrumStatus(): SpectrumStatus

export declare function getState(): PlayerState

export declare function getTrackList(url?: string | undefined | null): Promise<unknown>

export declare function initialize(config?: PlayerConfigOptions | undefined | null): void

export declare function loadFile(url: string, seq?: number | undefined | null): Promise<unknown>

export declare function loadMkvTrack(url: string, trackId: number, seq?: number | undefined | null): Promise<unknown>

export declare function pause(): void

export declare function pauseWithFade(savedVolume: number, durationMs: number): Promise<unknown>

export declare function play(): Promise<unknown>

export interface PlayerConfigOptions {
  audioBufferSecs?: number
  audioCacheSecs?: number
  audioDemuxerMaxMb?: number
  audioDemuxerBackMb?: number
  networkTimeoutSecs?: number
  playbackStallTimeoutSecs?: number
  httpProxy?: string
}

export interface PlayerEvent {
  event: string
  time?: number
  duration?: number
  state?: PlayerState
  reason?: string
  message?: string
  level?: string
  devices?: Array<AudioDevice>
  path?: string
  seq?: number
}

export interface PlayerState {
  playing: boolean
  paused: boolean
  duration: number
  timePos: number
}

export declare function playWithFade(targetVolume: number, durationMs: number): Promise<unknown>

export declare function prepareNextSource(url: string, trackId?: number | undefined | null, seq?: number | undefined | null): Promise<unknown>

export declare function registerEventHandler(callback: ((err: Error | null, arg: PlayerEvent) => any)): void

export declare function seek(time: number): Promise<unknown>

export declare function setAudioDevice(deviceName: string): Promise<unknown>

export declare function setEqualizer(gains: Array<number>): Promise<unknown>

export declare function setExclusiveOutput(exclusive: boolean): Promise<unknown>

export declare function setHttpProxy(proxy: string): void

export declare function setImpulseResponse(payload: any): Promise<unknown>

export declare function setImpulseResponseMix(mix: number): Promise<unknown>

export declare function setLoopFile(loopFile: boolean): void

export declare function setNetworkTimeout(seconds: number): void

export declare function setNormalizationGain(gainDb: number): Promise<unknown>

export declare function setSpeed(speed: number): Promise<unknown>

export declare function setStallTimeout(seconds: number): void

export declare function setVolume(volume: number): void

export interface SpectrumFrame {
  bins: Array<number>
  peak: number
  rms: number
  timestamp: number
}

export interface SpectrumOptions {
  bands?: number
  fps?: number
  minFrequency?: number
  maxFrequency?: number
  smoothing?: number
}

export interface SpectrumStatus {
  available: boolean
  running: boolean
  reason?: string
}

export declare function stop(): void

export interface TrackInfo {
  id: number
  type: string
  selected: boolean
  codec?: string
  title?: string
  lang?: string
}
