/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 运行时向已加载的 af 滤镜发送命令（如改 amix 权重），不重建整条滤镜链 */
export declare function afCommand(label: string, cmd: string, arg: string, target: string): void

/** 音频设备信息 */
export interface AudioDevice {
  name: string
  description: string
}

/** 取消当前淡入淡出 */
export declare function cancelFade(): void

/** 销毁播放器 */
export declare function destroy(): void

/**
 * 淡入淡出
 * 返回后 fade 在后台线程执行，完成时通过事件回调通知
 */
export declare function fade(from: number, to: number, durationMs: number): void

/** 获取音频设备列表，返回 Promise<AudioDevice[]>。设备枚举在工作线程执行。 */
export declare function getAudioDevices(): Promise<unknown>

/** 获取属性值（字符串形式） */
export declare function getProperty(name: string): string

/** 获取当前状态快照 */
export declare function getState(): PlayerState

/** 获取音轨列表，返回 Promise<TrackInfo[]>。track-list 属性读取在工作线程执行。 */
export declare function getTrackList(): Promise<unknown>

/** 初始化 libmpv 播放器 */
export declare function initialize(libPath: string, config?: PlayerConfigOptions | undefined | null): void

/** 检查 fade 是否正在执行 */
export declare function isFading(): boolean

/** 加载音频文件，返回 Promise<void>。在工作线程发命令，不阻塞主线程。 */
export declare function loadFile(url: string, seq?: number | undefined | null): Promise<unknown>

/** 加载 MKV 并选择音轨，返回 Promise<void>。 */
export declare function loadMkvTrack(url: string, trackId: number, seq?: number | undefined | null): Promise<unknown>

/** 暂停 */
export declare function pause(): void

/** 复合操作：淡出 → 暂停 → 恢复音量 */
export declare function pauseWithFade(savedVolume: number, durationMs: number): void

/** 播放，返回 Promise<void>。新文件起播的滤镜链构建在工作线程完成，不阻塞主线程。 */
export declare function play(): Promise<unknown>

/** 播放器配置选项（可选参数） */
export interface PlayerConfigOptions {
  cacheSecs?: number
  demuxerMaxMb?: number
  demuxerBackMb?: number
  audioBufferSecs?: number
  networkTimeoutSecs?: number
  httpProxy?: string
}

/** 播放器事件 */
export interface PlayerEvent {
  /** time-update / duration-change / state-change / playback-end / file-loaded / idle / error / log-message */
  type: string
  /** 事件关联的数值（time-pos、duration、volume 等） */
  value?: number
  /** 事件关联的布尔值（paused、playing 等） */
  flag?: boolean
  /** 事件关联的字符串（错误信息、end-file reason 等） */
  message?: string
  /** 事件关联的设备列表（audio-device-list-changed 时携带） */
  devices?: Array<AudioDevice>
  /** mpv 日志来源前缀（log-message 时携带） */
  prefix?: string
  /** mpv 日志等级（log-message 时携带） */
  level?: string
}

/** 播放器状态快照 */
export interface PlayerState {
  playing: boolean
  paused: boolean
  duration: number
  timePos: number
  volume: number
  speed: number
  idle: boolean
  path: string
  audioDevice: string
  audioTrackId: number
}

/** 复合操作：设置音量 0 → 播放 → 淡入，返回 Promise<void>。起播的滤镜链构建在工作线程完成。 */
export declare function playWithFade(targetVolume: number, durationMs: number): Promise<unknown>

/** 注册事件回调并启动事件循环 */
export declare function registerEventHandler(callback: ((err: Error | null, arg: PlayerEvent) => any)): void

/** 跳转（秒） */
export declare function seek(time: number): void

/** 设置音频输出设备，返回 Promise<void>。设备重建在工作线程执行，不阻塞主线程。 */
export declare function setAudioDevice(deviceName: string): Promise<unknown>

/** 设置音频滤镜 */
export declare function setAudioFilter(filter: string): void

/**
 * 异步设置音频滤镜，返回 Promise<void>。滤镜链重建在工作线程完成，
 * 不阻塞主线程，错误通过 Promise reject 抛回 JS 层。
 */
export declare function setAudioFilterAsync(filter: string): Promise<unknown>

/** 设置音轨 ID（file-loaded 后调用） */
export declare function setAudioTrack(trackId: number): void

/** 设置独占模式，返回 Promise<void>。音频输出重启在工作线程执行，不阻塞主线程。 */
export declare function setExclusive(exclusive: boolean): Promise<unknown>

/** 设置 HTTP 代理，空字符串表示直连 */
export declare function setHttpProxy(proxy: string): void

/** 设置文件循环（"inf" 无限循环，"no" 不循环），返回 Promise<void>。 */
export declare function setLoopFile(value: string): Promise<unknown>

/** 设置 force-media-title */
export declare function setMediaTitle(title: string): void

/** 设置网络超时（秒） */
export declare function setNetworkTimeout(seconds: number): void

/** 设置播放速度，返回 Promise<void>。滤镜链重建在工作线程完成，不阻塞主线程。 */
export declare function setSpeed(speed: number): Promise<unknown>

/** 设置音量（0-100） */
export declare function setVolume(volume: number): void

/**
 * 设置响度归一增益（dB），返回 Promise<void>。走 mpv 的 volume-gain 属性，不重建 af 链；
 * 老版 mpv 不支持时 Promise reject，由 JS 层回退到 af 滤镜方式。
 */
export declare function setVolumeGain(gainDb: number): Promise<unknown>

/** 停止 */
export declare function stop(): void

/** 音轨信息 */
export interface TrackInfo {
  id: number
  type: string
  codec: string
  title?: string
  lang?: string
}
