name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            build_script: npm run build:all
          - os: ubuntu-latest
            build_script: npm run build:all:linux
          - os: windows-latest
            build_script: npm run build:all:win

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: npm install

      - name: Install server dependencies
        run: cd server && pnpm install

      - name: Build server and app
        run: ${{ matrix.build_script }}

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --publish=always
